//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TuiguangEntities : DbContext
    {
        public TuiguangEntities()
            : base("name=TuiguangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcccessTable> AcccessTable { get; set; }
        public virtual DbSet<Scan> Scan { get; set; }
        public virtual DbSet<WeiXin> WeiXin { get; set; }
        public virtual DbSet<WeixinShowTrend> WeixinShowTrend { get; set; }
    }
}
